"""
Parser dispatch aliases grouped by domain.

These tables keep handler parser aliases centralized so new API additions
do not silently grow ad-hoc tuple checks across the parser.
"""

STATEMENT_FN_BY_DOMAIN = {
    "motion": {
        "animate",
        "Animate",
        "fade_in",
        "FadeIn",
        "fade_out",
        "FadeOut",
        "rotate",
        "Rotate",
        "scale",
        "Scale",
        "translate",
        "Translate",
        "animate_elevation",
        "AnimateElevation",
        "sequence",
        "Sequence",
        "parallel",
        "Parallel",
    },
    "navigation": {
        "navigate",
        "Navigate",
        "back",
        "Back",
        "pop_to_root",
        "PopToRoot",
        "clear_stack",
        "ClearStack",
        "replace",
        "Replace",
    },
    "capabilities": {
        "open_url",
        "OpenUrl",
        "launch_url",
        "LaunchUrl",
        "url_launcher",
        "URLLauncher",
        "check_connectivity",
        "CheckConnectivity",
        "connectivity_check",
        "ConnectivityCheck",
        "is_connected",
        "IsConnected",
        "check_location",
        "CheckLocation",
        "check_location_enabled",
        "CheckLocationEnabled",
        "location_check",
        "LocationCheck",
        "location_enabled",
        "LocationEnabled",
        "is_location_enabled",
        "IsLocationEnabled",
        "check_permission",
        "CheckPermission",
        "permission_check",
        "PermissionCheck",
        "clipboard_set",
        "ClipboardSet",
        "set_clipboard",
        "SetClipboard",
        "create_notification_channel",
        "CreateNotificationChannel",
        "notification_channel",
        "NotificationChannel",
        "notify",
        "Notify",
        "send_notification",
        "SendNotification",
        "request_permissions",
        "request_permission",
        "RequestPermissions",
        "RequestPermission",
    },
    "hybrid": {
        "observable",
        "Observable",
        "reactive_observable",
        "ReactiveObservable",
        "set_observable",
        "SetObservable",
        "reactive_set",
        "ReactiveSet",
        "derived",
        "Derived",
        "reactive_derived",
        "ReactiveDerived",
        "listen",
        "Listen",
        "reactive_listen",
        "ReactiveListen",
        "bind_text",
        "BindText",
        "reactive_bind_text",
        "ReactiveBindText",
    },
}

EXPR_FN_BY_DOMAIN = {
    "capabilities": {
        "permission_granted",
        "PermissionGranted",
        "has_permission",
        "HasPermission",
        "location_enabled",
        "LocationEnabled",
        "is_location_enabled",
        "IsLocationEnabled",
        "check_location",
        "CheckLocation",
        "check_location_enabled",
        "CheckLocationEnabled",
        "location_check",
        "LocationCheck",
        "notify_result",
        "NotifyResult",
        "notify_error",
        "NotifyError",
        "clipboard_get",
        "ClipboardGet",
        "get_clipboard",
        "GetClipboard",
    },
    "hybrid": {
        "observable_get",
        "ObservableGet",
        "reactive_get",
        "ReactiveGet",
    },
}
